"""Configuration management via pydantic-settings.

Loads application settings from environment variables or .env file with validation.
"""

from typing import Any, List, Literal, Optional
from pydantic import Field, field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    """Application configuration schema with validation and sensible defaults."""

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    # --- Telegram Configuration ---
    telegram_bot_token: str = Field(
        default="",
        alias="TELEGRAM_BOT_TOKEN",
        description="Bot token generated by @BotFather",
    )
    telegram_channel_id: str = Field(
        default="",
        alias="TELEGRAM_CHANNEL_ID",
        description="Channel username (e.g. @channel) or numeric ID",
    )
    admin_user_ids_input: Any = Field(
        default="",
        alias="ADMIN_USER_IDS",
        description="Comma-separated Telegram user IDs allowed to run admin commands",
    )

    @property
    def admin_user_ids(self) -> List[int]:
        """Parsed list of admin user IDs."""
        v = self.admin_user_ids_input
        if isinstance(v, str):
            if not v.strip():
                return []
            return [int(uid.strip()) for uid in v.split(",") if uid.strip().isdigit()]
        if isinstance(v, (list, set, tuple)):
            return [int(uid) for uid in v]
        return []

    # --- Storage Provider ---
    storage_provider: Literal["local", "terabox", "s3"] = Field(
        default="local",
        alias="STORAGE_PROVIDER",
    )

    # --- Local Storage Options ---
    local_storage_path: str = Field(
        default="./media_storage",
        alias="LOCAL_STORAGE_PATH",
    )
    local_storage_base_url: Optional[str] = Field(
        default=None,
        alias="LOCAL_STORAGE_BASE_URL",
        description="Public base URL for local file links, e.g. https://cdn.domain.com/videos",
    )

    # --- TeraBox Official Open Platform Options ---
    terabox_app_id: Optional[str] = Field(default=None, alias="TERABOX_APP_ID")
    terabox_app_key: Optional[str] = Field(default=None, alias="TERABOX_APP_KEY")
    terabox_access_token: Optional[str] = Field(default=None, alias="TERABOX_ACCESS_TOKEN")
    terabox_root_folder: str = Field(default="/", alias="TERABOX_ROOT_FOLDER")
    terabox_webhook_secret: Optional[str] = Field(default=None, alias="TERABOX_WEBHOOK_SECRET")

    # --- S3 Storage Options ---
    s3_endpoint_url: Optional[str] = Field(default=None, alias="S3_ENDPOINT_URL")
    s3_access_key: Optional[str] = Field(default=None, alias="S3_ACCESS_KEY")
    s3_secret_key: Optional[str] = Field(default=None, alias="S3_SECRET_KEY")
    s3_bucket_name: Optional[str] = Field(default=None, alias="S3_BUCKET_NAME")
    s3_region: str = Field(default="us-east-1", alias="S3_REGION")

    # --- Metadata APIs ---
    tmdb_api_key: Optional[str] = Field(default=None, alias="TMDB_API_KEY")
    omdb_api_key: Optional[str] = Field(default=None, alias="OMDB_API_KEY")
    metadata_language: str = Field(default="en", alias="METADATA_LANGUAGE")

    # --- Database ---
    database_url: str = Field(
        default="sqlite+aiosqlite:///./data/bot.db",
        alias="DATABASE_URL",
    )

    # --- Scheduler & Auto-Sync ---
    sync_interval_seconds: int = Field(default=300, alias="SYNC_INTERVAL_SECONDS")
    run_sync_on_startup: bool = Field(default=True, alias="RUN_SYNC_ON_STARTUP")

    # --- Publishing Policy ---
    enable_direct_video_upload: bool = Field(
        default=False,
        alias="ENABLE_DIRECT_VIDEO_UPLOAD",
        description="Strict safety guard: Only upload actual video if distribution rights are owned",
    )
    post_rate_limit_delay: float = Field(default=3.0, alias="POST_RATE_LIMIT_DELAY")
    max_publish_retries: int = Field(default=3, alias="MAX_PUBLISH_RETRIES")

    # --- Healthcheck & Webhook API ---
    health_check_host: str = Field(default="0.0.0.0", alias="HEALTH_CHECK_HOST")
    health_check_port: int = Field(default=8080, alias="HEALTH_CHECK_PORT")

    @field_validator("health_check_port", mode="before")
    @classmethod
    def resolve_port(cls, v):
        import os
        port_env = os.environ.get("PORT")
        if port_env and str(port_env).isdigit():
            return int(port_env)
        return int(v) if v else 8080

    # --- Logging ---
    log_level: str = Field(default="INFO", alias="LOG_LEVEL")
    log_file_path: str = Field(default="./logs/bot.log", alias="LOG_FILE_PATH")
    log_max_bytes: int = Field(default=10485760, alias="LOG_MAX_BYTES")
    log_backup_count: int = Field(default=5, alias="LOG_BACKUP_COUNT")

    def is_admin(self, user_id: int) -> bool:
        """Check if user_id is configured as an admin."""
        return user_id in self.admin_user_ids


# Global cached settings instance
_settings: Optional[Settings] = None


def get_settings() -> Settings:
    """Retrieve or initialize application settings."""
    global _settings
    if _settings is None:
        _settings = Settings()
    return _settings
